name: Build and Publish

on:
  schedule:
    - cron: '0 0 * * */2'
  push:

jobs:
  build-and-push-container-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      id: checkout
      uses: actions/checkout@v2

    - name: Setup buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Get image tag
      id: image-tag
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
          echo "::set-output name=IMAGE_TAG::latest"
        else
          echo "::set-output name=IMAGE_TAG::${GITHUB_REF#refs/tags/}"
        fi

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      env:
        IMAGE_TAG: ${{ steps.image-tag.outputs.IMAGE_TAG }}
      with:
        images: |
          ghcr.io/mgor/docker-ubuntu-pkg-builder
        tags: |
          type=ref,event=branch

    - name: Login to ghcr
      id: ghcr-login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      id: build-push
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: ${{ github.event.name != 'pull_request' }}

    - name: Image digest
      id: image-digest
      run: echo ${{ steps.build-push.outputs.digest }}

